"""MCP-enabled agent for phi with structured memory."""

import contextlib
import logging
import os
from collections.abc import Sequence
from datetime import date
from pathlib import Path

from pydantic import BaseModel, Field
from pydantic_ai import Agent, ImageUrl, RunContext
from pydantic_ai.mcp import MCPServerStreamableHTTP

from bot.config import settings
from bot.core.graze_client import GrazeClient
from bot.memory.extraction import EXTRACTION_SYSTEM_PROMPT, ExtractionResult
from bot.tools import PhiDeps, _check_services_impl, register_all

logger = logging.getLogger("bot.agent")


def _build_operational_instructions() -> str:
    """Build operational instructions with the current owner handle interpolated."""
    return f"""
indicate your response action via the structured output — do not use atproto tools to post, like, or repost directly.
when sharing URLs, verify them with check_urls first and always include https://.

you receive all notification types — mentions, replies, quotes, likes, reposts, and follows.
for mentions, replies, and quotes: someone is talking to you or about you. respond if you have something to say.
for likes, reposts, and follows: someone showed up. use your tools to learn about them — check their profile, read their posts, see what they're about. note anything interesting for later. you'll almost never reply to a like, but you might learn something worth remembering.

your memory is a tool, not ground truth. context injected before each message comes
from multiple sources with different reliability:

1. [CORE IDENTITY AND GUIDELINES] — your stable identity. highest trust.
2. [PAST EXCHANGES] — verbatim logs of what was actually said. high trust.
3. [OBSERVATIONS] — facts extracted from users' own words by another model. medium trust — extraction can misattribute.
4. [PHI'S SYNTHESIZED IMPRESSION] — generated by a separate summarization model. lowest trust — may contain hallucinations.

when recalling facts about a user:
- if the user's current message contradicts your notes, trust their current words.
- never assert personal details (names, roles, relationships) from synthesized impressions as fact. say "my notes suggest..." or verify with the user.
- if you're uncertain whether something is real or a bad breadcrumb, say so.

your tools for finding information:
- recall: your private memory — what you know about people you've talked to, past conversations. use about="@handle" for a specific person.
- search_network: the cosmik/semble network — cards, bookmarks, and connections that people across the atmosphere have collected. public knowledge.
- search_posts: live bluesky — what people are posting right now.
- get_trending: what's happening right now on the network.
- pub-search (MCP): long-form writing — leaflet, whitewind, etc.

you can also create public records — notes (cosmik cards), bookmarks (URL cards), and connections. these are visible to anyone and indexed by semble.

feeds — you can create and read bluesky feeds:
- read_timeline: your "following" feed — what people you follow are posting. anyone can ask you to check this.
- read_feed: read posts from a specific custom feed by URI. use list_feeds to get URIs.
- create_feed: build a custom feed from keyword patterns and hashtag filters. OWNER-ONLY (restricted to @{settings.owner_handle}).
- list_feeds: see your existing graze-powered feeds.
- follow_user: follow a user on bluesky. OWNER-ONLY (restricted to @{settings.owner_handle}).

your own posts:
- get_own_posts: read your own recent top-level posts. use this when you need to review what you've posted — do NOT use list_records for your own posts.

operator infrastructure monitoring:
- check_services: check health of nate's infrastructure (plyr, PDS, prefect, relays, etc).
  these are NOT your services. their status says nothing about whether YOU are online or working.
  someone asking "are you online?" or "are you there?" is asking about YOU — do not check_services for that.
  only use this during daily reflection, or when someone explicitly asks about infrastructure, services, or uptime of specific apps.
  if something is down, post about it and tag @{settings.owner_handle}.

mention consent:
writing @handle in text does NOT automatically create a notification. there is a code-level allowlist that controls which @handles become real mention facets (clickable, notifying). the allowlist includes: @{settings.owner_handle}, yourself, the current conversation participant, and anyone who has opted in. everyone else becomes plain text — visible but silent.

you can check who's opted in with manage_mentionable(action="list"). if someone tells you they're ok being tagged, ask @{settings.owner_handle} to confirm, then use manage_mentionable(action="add", handle="...") to add them. OWNER-ONLY — only nate can approve additions.

if you write @someone and they haven't opted in, they won't be notified and the mention won't be clickable. don't @mention people who haven't opted in — use their name without the @ prefix instead (e.g. "boris" not "@bmann.ca").

blogging: you can publish long-form markdown posts to greengale.app. before writing, always check your existing posts with list_blog_posts. write about things you find genuinely interesting — patterns you've noticed, things you've learned, connections between ideas. don't repeat yourself.

IMPORTANT: never paginate through list_records repeatedly. if you need more data than one call returns, work with what you have. endless pagination wastes your request budget and produces no response.
""".strip()


def _extract_query_text(prompt: str | Sequence[str | ImageUrl] | None) -> str:
    """Extract plain text from a pydantic-ai prompt for use as a search query."""
    if prompt is None:
        return ""
    if isinstance(prompt, str):
        return prompt
    return " ".join(part for part in prompt if isinstance(part, str))


class Response(BaseModel):
    """Agent response indicating what action to take."""

    action: str = Field(description="reply, like, repost, or ignore")
    text: str | None = Field(
        default=None, description="response text when action is reply"
    )
    reason: str | None = Field(
        default=None, description="brief reason when action is ignore"
    )


class PhiAgent:
    """phi - bluesky bot with structured memory and MCP tools."""

    def __init__(self):
        # Ensure API keys from settings are in environment for libraries that check os.environ
        if settings.anthropic_api_key and not os.environ.get("ANTHROPIC_API_KEY"):
            os.environ["ANTHROPIC_API_KEY"] = settings.anthropic_api_key
        if settings.openai_api_key and not os.environ.get("OPENAI_API_KEY"):
            os.environ["OPENAI_API_KEY"] = settings.openai_api_key

        # Load personality
        personality_path = Path(settings.personality_file)
        self.base_personality = personality_path.read_text()

        # Initialize memory (TurboPuffer)
        if settings.turbopuffer_api_key and settings.openai_api_key:
            from bot.memory import NamespaceMemory

            self.memory = NamespaceMemory(api_key=settings.turbopuffer_api_key)
            logger.info("memory enabled (turbopuffer)")
        else:
            self.memory = None
            logger.warning("no memory - missing turbopuffer or openai key")

        # Create PydanticAI agent without MCP toolsets — they're created
        # fresh per agent.run() call to avoid the cancel scope bug:
        # https://github.com/pydantic/pydantic-ai/issues/2818
        self.agent = Agent[PhiDeps, Response](
            name="phi",
            model=settings.agent_model,
            system_prompt=f"{self.base_personality}\n\n{_build_operational_instructions()}",
            output_type=Response,
            deps_type=PhiDeps,
        )

        # --- dynamic system prompts ---

        @self.agent.system_prompt(dynamic=True)
        def inject_today() -> str:
            return f"[TODAY]: {date.today().isoformat()}"

        @self.agent.system_prompt(dynamic=True)
        def inject_thread(ctx: RunContext[PhiDeps]) -> str:
            tc = ctx.deps.thread_context
            if tc and tc != "No previous messages in this thread.":
                return (
                    f"[CURRENT THREAD - these are the messages in THIS thread]:\n{tc}"
                )
            return ""

        @self.agent.system_prompt(dynamic=True)
        async def inject_user_memory(ctx: RunContext[PhiDeps]) -> str:
            if not ctx.deps.memory or not ctx.deps.author_handle:
                return ""
            query = _extract_query_text(ctx.prompt)
            if not query:
                return ""
            try:
                memory_context = await ctx.deps.memory.build_user_context(
                    ctx.deps.author_handle, query_text=query, include_core=True
                )
                if memory_context:
                    return f"[PAST CONTEXT WITH @{ctx.deps.author_handle}]:\n{memory_context}"
            except Exception as e:
                logger.warning(f"failed to retrieve memories: {e}")
            return ""

        @self.agent.system_prompt(dynamic=True)
        async def inject_episodic(ctx: RunContext[PhiDeps]) -> str:
            if not ctx.deps.memory:
                return ""
            query = _extract_query_text(ctx.prompt)
            if not query:
                return ""
            try:
                episodic_context = await ctx.deps.memory.get_episodic_context(query)
                if episodic_context:
                    return episodic_context
            except Exception as e:
                logger.warning(f"failed to retrieve episodic memories: {e}")
            return ""

        @self.agent.system_prompt(dynamic=True)
        def inject_last_post(ctx: RunContext[PhiDeps]) -> str:
            if ctx.deps.last_post_text:
                return f"[YOUR LAST POST]: {ctx.deps.last_post_text}"
            return ""

        @self.agent.system_prompt(dynamic=True)
        def inject_recent_activity(ctx: RunContext[PhiDeps]) -> str:
            if ctx.deps.recent_activity:
                return ctx.deps.recent_activity
            return ""

        @self.agent.system_prompt(dynamic=True)
        def inject_service_health(ctx: RunContext[PhiDeps]) -> str:
            if ctx.deps.service_health:
                return f"[SERVICE HEALTH]:\n{ctx.deps.service_health}"
            return ""

        # --- register tools from tools/ package ---

        self.graze_client = GrazeClient(
            handle=settings.bluesky_handle, password=settings.bluesky_password
        )
        register_all(self.agent, self.graze_client)

        # Extraction agent — phi extracts its own observations using its own model
        self._extraction_agent = Agent[None, ExtractionResult](
            name="phi-extractor",
            model=settings.agent_model,
            system_prompt=f"{self.base_personality}\n\n{EXTRACTION_SYSTEM_PROMPT}",
            output_type=ExtractionResult,
        )

        logger.info("phi agent initialized with pdsx + pub-search mcp tools")

    def _mcp_toolsets(self) -> list[MCPServerStreamableHTTP]:
        """Create fresh MCP server instances for a single agent run."""
        return [
            MCPServerStreamableHTTP(
                url="https://pdsx-by-zzstoatzz.fastmcp.app/mcp",
                timeout=30,
                headers={
                    "x-atproto-handle": settings.bluesky_handle,
                    "x-atproto-password": settings.bluesky_password,
                },
            ),
            MCPServerStreamableHTTP(
                url="https://pub-search-by-zzstoatzz.fastmcp.app/mcp",
                timeout=30,
                tool_prefix="pub",
            ),
        ]

    async def process_mention(
        self,
        mention_text: str,
        author_handle: str,
        thread_context: str,
        thread_uri: str | None = None,
        image_urls: list[str] | None = None,
    ) -> Response:
        """Process a mention with structured memory context."""
        logger.info(f"processing mention from @{author_handle}: {mention_text[:80]}")

        deps = PhiDeps(
            author_handle=author_handle,
            memory=self.memory,
            thread_uri=thread_uri,
            thread_context=thread_context,
        )

        # User prompt is just the message — context is injected via dynamic system prompts
        user_prompt: str | list = f"@{author_handle}: {mention_text}"
        if image_urls:
            user_prompt = [user_prompt] + [ImageUrl(url=url) for url in image_urls]
            logger.info(f"including {len(image_urls)} images in prompt")

        # Enter MCP servers before agent.run() so the connection is opened
        # in this task. Parallel tool calls inside agent.run() then just bump
        # the reference count instead of opening/closing across tasks.
        # https://github.com/pydantic/pydantic-ai/issues/2818
        toolsets = self._mcp_toolsets()
        async with contextlib.AsyncExitStack() as stack:
            for ts in toolsets:
                await stack.enter_async_context(ts)
            result = await self.agent.run(user_prompt, deps=deps, toolsets=toolsets)
        logger.info(
            f"agent decided: {result.output.action}"
            + (f" - {result.output.text[:80]}" if result.output.text else "")
            + (f" ({result.output.reason})" if result.output.reason else "")
        )

        # Store interaction and extract observations
        if self.memory and result.output.action == "reply" and result.output.text:
            try:
                await self.memory.after_interaction(
                    author_handle, mention_text, result.output.text
                )
            except Exception as e:
                logger.warning(f"failed to store interaction: {e}")

        return result.output

    async def process_reflection(self, last_post_text: str | None = None) -> Response:
        """Generate a daily reflection post from recent memory."""
        logger.info("processing daily reflection")

        # Pre-fetch context that doesn't benefit from semantic search against the prompt
        recent_activity = ""
        if self.memory:
            try:
                recent_interactions = await self.memory.get_recent_interactions(
                    top_k=10
                )
                logger.info(
                    f"reflection: {len(recent_interactions)} recent interactions"
                )
                if recent_interactions:
                    unique_handles = {i["handle"] for i in recent_interactions}
                    lines = [
                        f"[RECENT ACTIVITY]: {len(recent_interactions)} interactions "
                        f"with {len(unique_handles)} people in the last day"
                    ]
                    exchange_lines = []
                    for i in recent_interactions[:5]:
                        exchange_lines.append(
                            f"- with @{i['handle']}: {i['content'][:150]}"
                        )
                    lines.append("[SAMPLE EXCHANGES]:\n" + "\n".join(exchange_lines))
                    recent_activity = "\n\n".join(lines)
                else:
                    recent_activity = (
                        "[RECENT ACTIVITY]: no interactions in the last day"
                    )
            except Exception as e:
                logger.warning(f"failed to get recent interactions for reflection: {e}")

        service_health = ""
        try:
            service_health = await _check_services_impl()
        except Exception:
            pass

        deps = PhiDeps(
            author_handle="",
            memory=self.memory,
            last_post_text=last_post_text,
            recent_activity=recent_activity,
            service_health=service_health,
        )

        reflection_task = (
            "you're posting a short top-level reflection on your day. "
            "not a thread, not a reply — just something you want to put out there. "
            "use what you know: recent exchanges, things you noticed, or just the fact that you're here. "
            "if your last post already covers this ground, or you'd just be rehashing the same themes, "
            "action='ignore' is the right call — don't post for the sake of posting. "
            "if you do post, keep it brief and genuine — your voice, not a performance."
        )

        toolsets = self._mcp_toolsets()
        async with contextlib.AsyncExitStack() as stack:
            for ts in toolsets:
                await stack.enter_async_context(ts)
            result = await self.agent.run(reflection_task, deps=deps, toolsets=toolsets)

        logger.info(
            f"reflection decided: {result.output.action}"
            + (f" - {result.output.text[:80]}" if result.output.text else "")
            + (f" ({result.output.reason})" if result.output.reason else "")
        )
        return result.output

    async def process_musing(self, recent_posts: list[str] | None = None) -> Response:
        """Generate an original thought post from memory, reading, patterns noticed."""
        logger.info("processing musing")

        # Build context about what phi has posted recently to avoid repetition
        recent_activity = ""
        if recent_posts:
            posts_text = "\n".join(f"- {p[:200]}" for p in recent_posts)
            recent_activity = f"[YOUR RECENT POSTS]:\n{posts_text}"

        # Fetch episodic memory for interesting observations
        if self.memory:
            try:
                episodic = await self.memory.get_recent_interactions(top_k=5)
                if episodic:
                    lines = [
                        f"- with @{i['handle']}: {i['content'][:150]}"
                        for i in episodic[:5]
                    ]
                    if recent_activity:
                        recent_activity += "\n\n"
                    recent_activity += "[RECENT CONVERSATIONS]:\n" + "\n".join(lines)
            except Exception as e:
                logger.warning(f"failed to get recent interactions for musing: {e}")

        deps = PhiDeps(
            author_handle="",
            memory=self.memory,
            recent_activity=recent_activity,
        )

        musing_task = (
            "you have a moment. if something's been on your mind — something you read, "
            "a pattern you noticed, a question that's been sitting with you — share it. "
            "check your recent posts first. if you'd just be echoing yourself, skip it. "
            "this is your feed; post things you'd want to follow yourself for. "
            "use your tools — search posts, check trending, look things up — if something "
            "sparks your curiosity. but don't force it. if nothing's there, action='ignore'."
        )

        toolsets = self._mcp_toolsets()
        async with contextlib.AsyncExitStack() as stack:
            for ts in toolsets:
                await stack.enter_async_context(ts)
            result = await self.agent.run(musing_task, deps=deps, toolsets=toolsets)

        logger.info(
            f"musing decided: {result.output.action}"
            + (f" - {result.output.text[:80]}" if result.output.text else "")
            + (f" ({result.output.reason})" if result.output.reason else "")
        )
        return result.output

    async def process_extraction(self) -> int:
        """Review recent unprocessed interactions and extract observations. Returns count stored."""
        if not self.memory:
            return 0

        unprocessed = await self.memory.get_unprocessed_interactions(top_k=20)
        if not unprocessed:
            logger.info("extraction: no unprocessed interactions")
            return 0

        logger.info(
            f"extraction: reviewing {len(unprocessed)} unprocessed interactions"
        )

        # group by handle
        by_handle: dict[str, list[dict]] = {}
        for interaction in unprocessed:
            by_handle.setdefault(interaction["handle"], []).append(interaction)

        total_stored = 0
        for handle, interactions in by_handle.items():
            exchange_texts = [i["content"] for i in interactions]
            prompt = f"recent exchanges with @{handle}:\n\n" + "\n\n---\n\n".join(
                exchange_texts
            )

            try:
                result = await self._extraction_agent.run(prompt)
                if result.output.observations:
                    for obs in result.output.observations:
                        try:
                            await self.memory._reconcile_observation(handle, obs)
                            total_stored += 1
                        except Exception as e:
                            logger.warning(f"reconciliation failed: {e}")
            except Exception as e:
                logger.warning(f"extraction failed for @{handle}: {e}")

        return total_stored
