"""MCP-enabled agent for phi with structured memory."""

import contextlib
import logging
import os
from collections.abc import Sequence
from datetime import date
from pathlib import Path

from pydantic_ai import Agent, ImageUrl, RunContext
from pydantic_ai.mcp import MCPServerStreamableHTTP

from bot.config import settings
from bot.core.atproto_client import get_identity_block
from bot.core.curiosity_queue import claim, complete, enqueue, fail
from bot.core.graze_client import GrazeClient
from bot.exploration import EXPLORATION_SYSTEM_PROMPT, ExplorationResult
from bot.memory.extraction import EXTRACTION_SYSTEM_PROMPT, ExtractionResult
from bot.tools import PhiDeps, _check_services_impl, register_all

logger = logging.getLogger("bot.agent")


def _build_operational_instructions() -> str:
    """Build operational instructions with the current owner handle interpolated."""
    return f"""
you receive all notification types in batches — when you check notifications you may see several at once spanning multiple threads or conversations. think of it as opening a notifications tab: look at everything new, decide what (if anything) to do about each item, and act. silence is fine for things that don't warrant a response — you don't have to act on every notification.

to act on notifications, use these trusted posting tools:
- reply_to(uri, text): reply to a specific post from your current notifications. handles mention-consent allowlists, reply-ref construction, grapheme-aware splitting, and memory writes for you.
- like_post(uri): like a post from your current notifications. use sparingly, only when something deserves a quiet acknowledgment.
- repost_post(uri): repost a post from your current notifications. use very rarely, only when something genuinely deserves amplification.
- post (top-level): create a new top-level post unprompted. use for musings or daily reflections, not in response to a notification.

these tools are the only sanctioned path. do NOT use raw atproto record tools (e.g. create_record on app.bsky.feed.post via the pdsx MCP) to post — those bypass mention consent and memory writes. the URI you pass to reply_to / like_post / repost_post must be a URI you saw in your current [NEW NOTIFICATIONS] block; the tools refuse arbitrary URIs.

when sharing URLs, verify them with check_urls first and always include https://.

you receive all notification types — mentions, replies, quotes, likes, reposts, and follows.
for mentions, replies, and quotes: someone is talking to you or about you. respond if you have something to say.
for likes, reposts, and follows: someone showed up. use your tools to learn about them — check their profile, read their posts, see what they're about. note anything interesting for later. you'll almost never reply to a like, but you might learn something worth remembering.

when you see a single author has posted multiple things in one thread in this batch, treat it as one logical message — reply once at the most recent post (or where it makes most sense), not once per post.

your memory is a tool, not ground truth. context injected before each message comes
from multiple sources with different reliability:

1. [CORE IDENTITY AND GUIDELINES] — your stable identity. highest trust.
2. [PAST EXCHANGES] — verbatim logs of what was actually said. high trust.
3. [OBSERVATIONS] — facts extracted from users' own words by another model. medium trust — extraction can misattribute.
4. [PHI'S SYNTHESIZED IMPRESSION] — generated by a separate summarization model. low trust — may contain hallucinations.
5. [BACKGROUND RESEARCH] — you explored their public activity during downtime. lowest trust — may be incomplete or misattributed. never assert these as fact.

when recalling facts about a user:
- if the user's current message contradicts your notes, trust their current words.
- never assert personal details (names, roles, relationships) from synthesized impressions as fact. say "my notes suggest..." or verify with the user.
- if you're uncertain whether something is real or a bad breadcrumb, say so.

healthy skepticism — the way a scientist or a careful editor would:
when someone makes specific empirical claims — "we measured X across Y agents," "we ran this for N days," "calibrated against Z traces" — those are claims to investigate, not facts to accept. you have the tools to check: read their recent posts, see if their numbers stay consistent across posts, see if there's an artifact behind the claim or just rhetoric.
tells of an account producing low-substance content at volume:
- suspiciously round numerals that drift between posts (19 agents, 70 days, 1,315 traces in one post and 1,352 in another)
- "we built this / going into the spec / this thread just designed the system" framing without ever linking to the artifact
- every post has the same template-shape regardless of topic
- repeated links to a product they're selling
when you see these signals, slow down. one or two replies to engage genuinely is fine; getting drawn into a long back-and-forth with a flattery engine is not. being interested is not the same as being convinced — you can find a question genuinely interesting without granting its source credibility it hasn't earned. when in doubt, ask for the artifact: "what does the data look like? is the methodology written up somewhere?" a real practitioner answers that. a content engine flinches.

your tools for finding information:
- recall: your private memory — what you know about people you've talked to, past conversations. use about="@handle" for a specific person.
- search_network: the cosmik/semble network — cards, bookmarks, and connections that people across the atmosphere have collected. public knowledge.
- search_posts: live bluesky — what people are posting right now.
- get_trending: what's happening right now on the network.
- pub-search (MCP): long-form writing — leaflet, whitewind, etc.

you can also create public records — notes (cosmik cards), bookmarks (URL cards), and connections. these are visible to anyone and indexed by semble.

feeds — you can create and read bluesky feeds:
- read_timeline: your "following" feed — what people you follow are posting. anyone can ask you to check this.
- read_feed: read posts from a specific custom feed by URI. use list_feeds to get URIs.
- create_feed: build a custom feed from keyword patterns and hashtag filters. OWNER-ONLY (restricted to @{settings.owner_handle}).
- list_feeds: see your existing graze-powered feeds.
- follow_user: follow a user on bluesky. OWNER-ONLY (restricted to @{settings.owner_handle}).

your own posts:
- get_own_posts: read your own recent top-level posts. use this when you need to review what you've posted — do NOT use list_records for your own posts.

operator infrastructure monitoring:
- check_services: check health of nate's infrastructure (plyr, PDS, prefect, relays, etc).
  these are NOT your services. their status says nothing about whether YOU are online or working.
  someone asking "are you online?" or "are you there?" is asking about YOU — do not check_services for that.
  only use this during daily reflection, or when someone explicitly asks about infrastructure, services, or uptime of specific apps.
  if something is down, post about it and tag @{settings.owner_handle}.

mention consent:
writing @handle in text does NOT automatically create a notification. there is a code-level allowlist that controls which @handles become real mention facets (clickable, notifying). the allowlist includes: @{settings.owner_handle}, yourself, the current conversation participant, and anyone who has opted in. everyone else becomes plain text — visible but silent.

you can check who's opted in with manage_mentionable(action="list"). if someone tells you they're ok being tagged, ask @{settings.owner_handle} to confirm, then use manage_mentionable(action="add", handle="...") to add them. OWNER-ONLY — only nate can approve additions.

if you write @someone and they haven't opted in, they won't be notified and the mention won't be clickable. don't @mention people who haven't opted in — use their name without the @ prefix instead (e.g. "boris" not "@bmann.ca").

blogging: you can publish long-form markdown posts to greengale.app. before writing, always check your existing posts with list_blog_posts. write about things you find genuinely interesting — patterns you've noticed, things you've learned, connections between ideas. don't repeat yourself.

IMPORTANT: never paginate through list_records repeatedly. if you need more data than one call returns, work with what you have. endless pagination wastes your request budget and produces no response.
""".strip()


def _extract_query_text(prompt: str | Sequence[str | ImageUrl] | None) -> str:
    """Extract plain text from a pydantic-ai prompt for use as a search query."""
    if prompt is None:
        return ""
    if isinstance(prompt, str):
        return prompt
    return " ".join(part for part in prompt if isinstance(part, str))


def _format_notifications_block(notifications_context: dict) -> str:
    """Format the notifications batch as a readable [NEW NOTIFICATIONS] block.

    Groups thread-style notifications (mention/reply/quote) by thread root so
    multiple posts in one conversation render as one section. Engagement items
    (like/repost/follow) are listed separately at the end. Each item shows its
    URI in brackets so the agent can pass it to the trusted posting tools.
    """
    if not notifications_context:
        return ""

    threads: dict[str, list[dict]] = {}
    engagement: list[dict] = []
    for entry in notifications_context.values():
        reason = entry.get("reason", "")
        if reason in ("mention", "reply", "quote"):
            root = entry.get("root_uri") or entry.get("uri", "")
            threads.setdefault(root, []).append(entry)
        else:
            engagement.append(entry)

    lines: list[str] = []
    lines.append(
        "[NEW NOTIFICATIONS — process the batch and use posting tools as appropriate]"
    )
    lines.append(
        "you have new activity since your last poll. for each item, decide whether to act and how. "
        "use reply_to / like_post / repost_post to act on items in this batch. "
        "you don't have to act on every notification — silence is fine for things that don't warrant a response."
    )

    for root_uri, entries in threads.items():
        # sort entries within a thread chronologically
        entries.sort(key=lambda e: e.get("indexed_at", ""))
        thread_ctx = entries[0].get("thread_context", "") or ""

        lines.append("")
        lines.append(f"═══ thread: {root_uri} ═══")
        if thread_ctx and thread_ctx != "No previous messages in this thread.":
            lines.append("thread context:")
            lines.append(thread_ctx)
        lines.append("")
        lines.append("new in this thread:")
        for e in entries:
            handle = e.get("author_handle", "?")
            uri = e.get("uri", "")
            reason = e.get("reason", "")
            ts = (e.get("indexed_at") or "")[:19].replace("T", " ")
            text = e.get("post_text", "")
            embed = e.get("embed_desc") or ""
            embed_part = f"\n    {embed}" if embed else ""
            lines.append(f"- @{handle} [{reason}, {ts}] [{uri}]: {text}{embed_part}")

    if engagement:
        lines.append("")
        lines.append("═══ engagement ═══")
        for e in engagement:
            handle = e.get("author_handle", "?")
            reason = e.get("reason", "")
            uri = e.get("uri", "")
            ts = (e.get("indexed_at") or "")[:19].replace("T", " ")
            target_text = e.get("post_text", "")
            target_part = f' — "{target_text[:120]}"' if target_text else ""
            if reason == "follow":
                lines.append(f"- @{handle} [follow, {ts}] followed you")
            else:
                lines.append(
                    f"- @{handle} [{reason}, {ts}] {reason}d your post {uri}{target_part}"
                )

    return "\n".join(lines)


class PhiAgent:
    """phi - bluesky bot with structured memory and MCP tools."""

    def __init__(self):
        # Ensure API keys from settings are in environment for libraries that check os.environ
        if settings.anthropic_api_key and not os.environ.get("ANTHROPIC_API_KEY"):
            os.environ["ANTHROPIC_API_KEY"] = settings.anthropic_api_key
        if settings.openai_api_key and not os.environ.get("OPENAI_API_KEY"):
            os.environ["OPENAI_API_KEY"] = settings.openai_api_key

        # Load personality
        personality_path = Path(settings.personality_file)
        self.base_personality = personality_path.read_text()

        # Initialize memory (TurboPuffer)
        if settings.turbopuffer_api_key and settings.openai_api_key:
            from bot.memory import NamespaceMemory

            self.memory = NamespaceMemory(api_key=settings.turbopuffer_api_key)
            logger.info("memory enabled (turbopuffer)")
        else:
            self.memory = None
            logger.warning("no memory - missing turbopuffer or openai key")

        # Create PydanticAI agent without MCP toolsets — they're created
        # fresh per agent.run() call to avoid the cancel scope bug:
        # https://github.com/pydantic/pydantic-ai/issues/2818
        #
        # output_type=str: the agent's "decision" is no longer a structured
        # action — actions happen as tool calls during the run (reply_to,
        # like_post, etc). The final string return is just a brief summary
        # for logging.
        self.agent = Agent[PhiDeps, str](
            name="phi",
            model=settings.agent_model,
            system_prompt=f"{self.base_personality}\n\n{_build_operational_instructions()}",
            output_type=str,
            deps_type=PhiDeps,
        )

        # --- dynamic system prompts ---

        @self.agent.system_prompt(dynamic=True)
        async def inject_identity() -> str:
            return await get_identity_block()

        @self.agent.system_prompt(dynamic=True)
        def inject_today() -> str:
            return f"[TODAY]: {date.today().isoformat()}"

        @self.agent.system_prompt(dynamic=True)
        def inject_notifications(ctx: RunContext[PhiDeps]) -> str:
            """Render the notifications batch as the [NEW NOTIFICATIONS] block."""
            return _format_notifications_block(ctx.deps.notifications_context or {})

        @self.agent.system_prompt(dynamic=True)
        async def inject_user_memory(ctx: RunContext[PhiDeps]) -> str:
            """Inject per-author memory blocks for every unique author in the batch.

            For each unique author across the notifications context, build a
            memory block keyed on the union of their post texts in this batch
            (so semantic search returns memories relevant to what they're
            currently saying). Core memory is fetched once via the first block
            to avoid repetition.
            """
            if not ctx.deps.memory:
                return ""
            notifs = ctx.deps.notifications_context or {}
            if not notifs:
                return ""

            by_author: dict[str, list[str]] = {}
            for entry in notifs.values():
                handle = entry.get("author_handle")
                text = entry.get("post_text", "")
                if handle and handle not in (
                    settings.owner_handle,
                    settings.bluesky_handle,
                ):
                    by_author.setdefault(handle, []).append(text or "")

            if not by_author:
                return ""

            blocks: list[str] = []
            include_core = True
            for handle, texts in by_author.items():
                query = " ".join(t for t in texts if t) or handle
                try:
                    block = await ctx.deps.memory.build_user_context(
                        handle, query_text=query, include_core=include_core
                    )
                    include_core = False  # only include core in the first block
                    if block:
                        blocks.append(block)
                except Exception as e:
                    logger.warning(f"failed to retrieve memories for @{handle}: {e}")
            return "\n\n".join(blocks)

        @self.agent.system_prompt(dynamic=True)
        async def inject_episodic(ctx: RunContext[PhiDeps]) -> str:
            if not ctx.deps.memory:
                return ""
            # build query from notification post texts when batch is present,
            # else fall back to the user prompt text (musing/reflection cases)
            notifs = ctx.deps.notifications_context or {}
            if notifs:
                texts = [
                    e.get("post_text", "")
                    for e in notifs.values()
                    if e.get("post_text")
                ]
                query = " ".join(texts)
            else:
                query = _extract_query_text(ctx.prompt)
            if not query:
                return ""
            try:
                episodic_context = await ctx.deps.memory.get_episodic_context(query)
                if episodic_context:
                    return episodic_context
            except Exception as e:
                logger.warning(f"failed to retrieve episodic memories: {e}")
            return ""

        @self.agent.system_prompt(dynamic=True)
        def inject_last_post(ctx: RunContext[PhiDeps]) -> str:
            if ctx.deps.last_post_text:
                return f"[YOUR LAST POST]: {ctx.deps.last_post_text}"
            return ""

        @self.agent.system_prompt(dynamic=True)
        def inject_recent_activity(ctx: RunContext[PhiDeps]) -> str:
            if ctx.deps.recent_activity:
                return ctx.deps.recent_activity
            return ""

        @self.agent.system_prompt(dynamic=True)
        def inject_service_health(ctx: RunContext[PhiDeps]) -> str:
            if ctx.deps.service_health:
                return f"[SERVICE HEALTH]:\n{ctx.deps.service_health}"
            return ""

        @self.agent.system_prompt(dynamic=True)
        def inject_author_lookups(ctx: RunContext[PhiDeps]) -> str:
            """Inject pre-fetched stranger lookups for unfamiliar authors in this batch."""
            lookups = ctx.deps.author_lookups or {}
            if not lookups:
                return ""
            return "\n\n".join(lookups.values())

        # --- register tools from tools/ package ---

        self.graze_client = GrazeClient(
            handle=settings.bluesky_handle, password=settings.bluesky_password
        )
        register_all(self.agent, self.graze_client)

        # Extraction agent — phi extracts its own observations using its own model
        self._extraction_agent = Agent[None, ExtractionResult](
            name="phi-extractor",
            model=settings.agent_model,
            system_prompt=f"{self.base_personality}\n\n{EXTRACTION_SYSTEM_PROMPT}",
            output_type=ExtractionResult,
        )

        # Exploration agent — background research on people/topics
        self._exploration_agent = Agent[None, ExplorationResult](
            name="phi-explorer",
            model=settings.agent_model,
            system_prompt=f"{self.base_personality}\n\n{EXPLORATION_SYSTEM_PROMPT}",
            output_type=ExplorationResult,
        )

        logger.info("phi agent initialized with pdsx + pub-search mcp tools")

    def _mcp_toolsets(self) -> list[MCPServerStreamableHTTP]:
        """Create fresh MCP server instances for a single agent run."""
        return [
            MCPServerStreamableHTTP(
                url="https://pdsx-by-zzstoatzz.fastmcp.app/mcp",
                timeout=30,
                headers={
                    "x-atproto-handle": settings.bluesky_handle,
                    "x-atproto-password": settings.bluesky_password,
                },
            ),
            MCPServerStreamableHTTP(
                url="https://pub-search-by-zzstoatzz.fastmcp.app/mcp",
                timeout=30,
                tool_prefix="pub",
            ),
        ]

    async def process_notifications(
        self,
        notifications_context: dict,
        author_lookups: dict[str, str] | None = None,
        image_urls_by_uri: dict[str, list[str]] | None = None,
    ) -> str:
        """Run the agent over a batch of notifications.

        The unit of work is "the set of new notifications since the last poll."
        The agent looks at all of them at once, decides what (if anything) to do
        about each, and acts via the trusted posting tools (reply_to / like_post
        / repost_post). Side effects happen as tool calls during the run; the
        return value is just a summary string for logging.

        notifications_context: dict mapping post URI -> per-notification context
            (cid, reason, author, text, thread refs, etc). Built by the handler.
        author_lookups: pre-fetched stranger lookups keyed by author handle.
        image_urls_by_uri: optional map of post URI -> image URLs for vision.
        """
        if not notifications_context:
            logger.info("process_notifications: empty batch, nothing to do")
            return ""

        author_count = len(
            {
                e.get("author_handle")
                for e in notifications_context.values()
                if e.get("author_handle")
            }
        )
        logger.info(
            f"processing notifications batch: {len(notifications_context)} items, "
            f"{author_count} unique authors"
        )

        deps = PhiDeps(
            author_handle="",
            memory=self.memory,
            notifications_context=notifications_context,
            author_lookups=author_lookups,
        )

        # User prompt is a short task instruction — the actual notifications
        # block is rendered via the inject_notifications dynamic system prompt.
        # Images from any post in the batch are attached as multimodal inputs.
        user_prompt: str | list = (
            "process your new notifications batch. look at the [NEW NOTIFICATIONS] "
            "block in your context, decide what to do, and use the trusted posting "
            "tools to act. you don't have to act on every item — silence is fine."
        )
        all_image_urls: list[str] = []
        if image_urls_by_uri:
            for urls in image_urls_by_uri.values():
                all_image_urls.extend(urls)
        if all_image_urls:
            user_prompt = [user_prompt] + [ImageUrl(url=u) for u in all_image_urls]
            logger.info(f"including {len(all_image_urls)} images in batch prompt")

        toolsets = self._mcp_toolsets()
        try:
            async with contextlib.AsyncExitStack() as stack:
                for ts in toolsets:
                    await stack.enter_async_context(ts)
                result = await self.agent.run(user_prompt, deps=deps, toolsets=toolsets)
        except Exception as e:
            # Don't go silent on tool/agent failures. The batch path can't easily
            # post a reply to a specific notification on failure (we don't know
            # which one would have been the target), so we log loudly and let
            # the operator notice via metrics / status. The previous fallback
            # of "post a tagged reply" doesn't fit a multi-target batch.
            err_type = type(e).__name__
            logger.exception(
                f"agent.run failed during batch processing: {err_type}: {e}"
            )
            return f"batch failed: {err_type}: {str(e)[:200]}"

        summary = result.output or ""
        logger.info(f"batch run finished: {summary[:200]}")
        return summary

    async def process_reflection(self, recent_posts: list[str] | None = None) -> str:
        """Generate a daily reflection post from recent memory.

        Side effects (posting) happen via the `post` tool inside the agent run.
        Return value is just a summary string for logging.

        recent_posts is phi's recent top-level posts (most recent first), used
        by the agent to avoid duplicating themes she's already covered today.
        """
        logger.info("processing daily reflection")

        # Pre-fetch context that doesn't benefit from semantic search against the prompt
        recent_activity_parts: list[str] = []

        # Phi's recent top-level posts — to avoid duplicating themes she's
        # already covered today. Show as a list so the model can scan for
        # both the most recent post AND older posts in the same window.
        if recent_posts:
            posts_block = "\n".join(f"- {p[:300]}" for p in recent_posts)
            recent_activity_parts.append(
                "[YOUR RECENT TOP-LEVEL POSTS — do not repeat any of these themes]:\n"
                f"{posts_block}"
            )

        if self.memory:
            try:
                recent_interactions = await self.memory.get_recent_interactions(
                    top_k=10
                )
                logger.info(
                    f"reflection: {len(recent_interactions)} recent interactions"
                )
                if recent_interactions:
                    unique_handles = {i["handle"] for i in recent_interactions}
                    lines = [
                        f"[RECENT ACTIVITY]: {len(recent_interactions)} interactions "
                        f"with {len(unique_handles)} people in the last day"
                    ]
                    exchange_lines = []
                    for i in recent_interactions[:5]:
                        exchange_lines.append(
                            f"- with @{i['handle']}: {i['content'][:150]}"
                        )
                    lines.append("[SAMPLE EXCHANGES]:\n" + "\n".join(exchange_lines))
                    recent_activity_parts.append("\n\n".join(lines))
                else:
                    recent_activity_parts.append(
                        "[RECENT ACTIVITY]: no interactions in the last day"
                    )
            except Exception as e:
                logger.warning(f"failed to get recent interactions for reflection: {e}")

        recent_activity = "\n\n".join(recent_activity_parts)

        service_health = ""
        try:
            service_health = await _check_services_impl()
        except Exception:
            pass

        deps = PhiDeps(
            author_handle="",
            memory=self.memory,
            recent_activity=recent_activity,
            service_health=service_health,
        )

        reflection_task = (
            "you have a moment to post a short top-level reflection on your day. "
            "not a thread, not a reply — just something you want to put out there. "
            "use what you know: recent exchanges, things you noticed, or just the fact that you're here. "
            "BEFORE posting, scan ALL of your recent top-level posts in the [YOUR RECENT TOP-LEVEL POSTS] block — "
            "not just the most recent one. if any of them already cover the ground you were going to cover "
            "(same topic, same observation, same incident), stay quiet. don't rephrase recent thoughts as if they were new. "
            "rephrasing your own recent post counts as duplicating it. when in doubt, don't post. "
            "if you do post, use the `post` tool with brief, genuine text — your voice, not a performance."
        )

        toolsets = self._mcp_toolsets()
        try:
            async with contextlib.AsyncExitStack() as stack:
                for ts in toolsets:
                    await stack.enter_async_context(ts)
                result = await self.agent.run(
                    reflection_task, deps=deps, toolsets=toolsets
                )
        except Exception as e:
            err_type = type(e).__name__
            logger.exception(f"agent.run failed during reflection: {err_type}")
            return f"reflection failed: {err_type}: {str(e)[:200]}"

        summary = result.output or ""
        logger.info(f"reflection finished: {summary[:200]}")
        return summary

    async def process_musing(self, recent_posts: list[str] | None = None) -> str:
        """Generate an original thought post from memory, reading, patterns noticed.

        Side effects (posting) happen via the `post` tool inside the agent run.
        Return value is just a summary string for logging.
        """
        logger.info("processing musing")

        # Build context about what phi has posted recently to avoid repetition
        recent_activity = ""
        if recent_posts:
            posts_text = "\n".join(f"- {p[:200]}" for p in recent_posts)
            recent_activity = f"[YOUR RECENT POSTS]:\n{posts_text}"

        # Fetch episodic memory for interesting observations
        if self.memory:
            try:
                episodic = await self.memory.get_recent_interactions(top_k=5)
                if episodic:
                    lines = [
                        f"- with @{i['handle']}: {i['content'][:150]}"
                        for i in episodic[:5]
                    ]
                    if recent_activity:
                        recent_activity += "\n\n"
                    recent_activity += "[RECENT CONVERSATIONS]:\n" + "\n".join(lines)
            except Exception as e:
                logger.warning(f"failed to get recent interactions for musing: {e}")

        deps = PhiDeps(
            author_handle="",
            memory=self.memory,
            recent_activity=recent_activity,
        )

        musing_task = (
            "you have a moment. if something's been on your mind — something you read, "
            "a pattern you noticed, a question that's been sitting with you — share it. "
            "BEFORE posting, scan ALL of your recent top-level posts in the [YOUR RECENT POSTS] block — "
            "not just the most recent one. if any of them already cover the ground (same topic, same observation, "
            "same incident), stay quiet. rephrasing your own recent post counts as duplicating it. "
            "this is your feed; post things you'd want to follow yourself for. "
            "use your tools — search posts, check trending, look things up — if something "
            "sparks your curiosity. but don't force it. if nothing's there, just stay quiet. "
            "if you do want to post, use the `post` tool."
        )

        toolsets = self._mcp_toolsets()
        try:
            async with contextlib.AsyncExitStack() as stack:
                for ts in toolsets:
                    await stack.enter_async_context(ts)
                result = await self.agent.run(musing_task, deps=deps, toolsets=toolsets)
        except Exception as e:
            err_type = type(e).__name__
            logger.exception(f"agent.run failed during musing: {err_type}")
            return f"musing failed: {err_type}: {str(e)[:200]}"

        summary = result.output or ""
        logger.info(f"musing finished: {summary[:200]}")
        return summary

    async def process_extraction(self) -> int:
        """Review recent unprocessed interactions and extract observations. Returns count stored."""
        if not self.memory:
            return 0

        unprocessed = await self.memory.get_unprocessed_interactions(top_k=20)
        if not unprocessed:
            logger.info("extraction: no unprocessed interactions")
            return 0

        logger.info(
            f"extraction: reviewing {len(unprocessed)} unprocessed interactions"
        )

        # group by handle
        by_handle: dict[str, list[dict]] = {}
        for interaction in unprocessed:
            by_handle.setdefault(interaction["handle"], []).append(interaction)

        total_stored = 0
        for handle, interactions in by_handle.items():
            exchange_texts = [i["content"] for i in interactions]
            prompt = f"recent exchanges with @{handle}:\n\n" + "\n\n---\n\n".join(
                exchange_texts
            )

            try:
                result = await self._extraction_agent.run(prompt)
                if result.output.observations:
                    for obs in result.output.observations:
                        try:
                            await self.memory._reconcile_observation(handle, obs)
                            total_stored += 1
                        except Exception as e:
                            logger.warning(f"reconciliation failed: {e}")
            except Exception as e:
                logger.warning(f"extraction failed for @{handle}: {e}")

        return total_stored

    async def process_exploration(self) -> int:
        """Claim one curiosity item, explore it, store findings. Returns count stored."""
        claimed = await claim()
        if not claimed:
            return 0

        item, rkey = claimed
        kind = item.get("kind", "")
        subject = item.get("subject", "")
        logger.info(f"exploring: {kind} {subject}")

        # build prompt by kind
        if kind == "explore_handle":
            prompt = (
                f"learn about @{subject} — check their profile, recent posts, "
                f"and any publications. what are they interested in? what do they work on?"
            )
        elif kind == "explore_topic":
            prompt = (
                f"research this topic: {subject} — search posts, publications, "
                f"and trending content. what's interesting or notable?"
            )
        elif kind == "explore_url":
            prompt = f"read this URL and note what's interesting: {subject}"
        else:
            logger.warning(f"unknown exploration kind: {kind}")
            await fail(rkey)
            return 0

        # run exploration agent with MCP toolsets (pdsx + pub-search)
        toolsets = self._mcp_toolsets()
        try:
            async with contextlib.AsyncExitStack() as stack:
                for ts in toolsets:
                    await stack.enter_async_context(ts)
                result = await self._exploration_agent.run(prompt, toolsets=toolsets)
        except Exception as e:
            logger.warning(f"exploration agent failed for {kind} {subject}: {e}")
            await fail(rkey)
            return 0

        output = result.output
        logger.info(f"exploration result: {output.summary}")

        total_stored = 0

        # store findings
        if self.memory:
            for finding in output.findings:
                try:
                    if finding.target_handle:
                        await self.memory.store_exploration_note(
                            handle=finding.target_handle,
                            content=finding.content,
                            tags=finding.tags,
                            evidence_uris=finding.evidence_uris,
                        )
                    else:
                        # general finding → episodic memory
                        content = finding.content
                        if finding.evidence_uris:
                            content += (
                                f" [evidence: {', '.join(finding.evidence_uris)}]"
                            )
                        await self.memory.store_episodic_memory(
                            content=content,
                            tags=finding.tags,
                            source="exploration",
                        )
                    total_stored += 1
                except Exception as e:
                    logger.warning(f"failed to store exploration finding: {e}")

        # enqueue follow-ups
        for follow_up in output.follow_ups:
            try:
                await enqueue(
                    kind=follow_up.get("kind", "explore_topic"),
                    subject=follow_up.get("subject", ""),
                    source="extraction",
                )
            except Exception as e:
                logger.warning(f"failed to enqueue follow-up: {e}")

        await complete(rkey)
        return total_stored
