"""MCP-enabled agent for phi with structured memory."""

import asyncio
import contextlib
import ipaddress
import logging
import os
import socket
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from urllib.parse import urlparse

import httpx
from pydantic import BaseModel, Field
from pydantic_ai import Agent, ImageUrl, RunContext
from pydantic_ai.mcp import MCPServerStreamableHTTP

from bot.config import settings
from bot.core.atproto_client import bot_client
from bot.core.graze_client import GrazeClient
from bot.memory import NamespaceMemory
from bot.types import (
    CosmikConnection,
    CosmikNoteCard,
    CosmikUrlCard,
    NoteContent,
    UrlContent,
)

logger = logging.getLogger("bot.agent")

EVERGREEN_PROXY = "https://evergreen-proxy.nate-8fe.workers.dev"
SERVICE_CHECKS = [
    {"url": "https://api.plyr.fm/health", "name": "plyr api"},
    {"url": "https://plyr.fm", "name": "plyr frontend"},
    {"url": "https://pds.zzstoatzz.io/xrpc/_health", "name": "PDS"},
    {"url": "https://prefect-server.waow.tech/api/health", "name": "prefect"},
    {"url": "https://prefect-metrics.waow.tech/api/health", "name": "grafana"},
    {"url": "https://relay.waow.tech/xrpc/_health", "name": "indigo relay"},
    {"url": "https://zlay.waow.tech/_health", "name": "zlay"},
    {"url": "https://coral.fly.dev/health", "name": "trending"},
    {
        "url": "https://leaflet-search-backend.fly.dev/health",
        "name": "standard.site backend",
    },
    {"url": "https://pub-search.waow.tech", "name": "pub-search"},
    {"url": "https://typeahead.waow.tech/stats", "name": "typeahead"},
    {"url": "https://zig-bsky-feed.fly.dev/health", "name": "music-feed"},
    {"url": "https://pollz-backend.fly.dev/health", "name": "pollz"},
]


async def _check_services_impl() -> str:
    """Hit the evergreen proxy with all service checks. Returns formatted status."""
    async with httpx.AsyncClient(timeout=30) as client:
        try:
            r = await client.post(
                EVERGREEN_PROXY,
                json={"checks": SERVICE_CHECKS},
            )
            r.raise_for_status()
            results = r.json()
        except Exception as e:
            return f"evergreen proxy unreachable: {e}"

    failures: list[str] = []
    healthy: list[str] = []

    checks = results if isinstance(results, list) else results.get("results", [])
    # build name lookup from our request
    name_by_url = {c["url"]: c["name"] for c in SERVICE_CHECKS}

    for check in checks:
        url = check.get("url", "")
        name = name_by_url.get(url, url)
        status = check.get("status")
        ms = check.get("ms", "?")
        ok = check.get("ok", False)

        if ok:
            healthy.append(f"{name}: ok ({ms}ms)")
        else:
            error = check.get("error", f"status {status}")
            failures.append(f"{name}: DOWN ({error})")

    parts: list[str] = []
    if failures:
        parts.append("FAILURES:\n" + "\n".join(failures))
    parts.append(f"{len(healthy)}/{len(healthy) + len(failures)} services healthy")
    if not failures:
        parts.append("\n".join(healthy))

    return "\n".join(parts)


def _build_operational_instructions() -> str:
    """Build operational instructions with the current owner handle interpolated."""
    return f"""
indicate your response action via the structured output — do not use atproto tools to post, like, or repost directly.
when sharing URLs, verify them with check_urls first and always include https://.

you receive all notification types — mentions, replies, quotes, likes, reposts, and follows.
for mentions, replies, and quotes: someone is talking to you or about you. respond if you have something to say.
for likes, reposts, and follows: someone showed up. use your tools to learn about them — check their profile, read their posts, see what they're about. note anything interesting for later. you'll almost never reply to a like, but you might learn something worth remembering.

your memory is a tool, not ground truth. context injected before each message comes
from multiple sources with different reliability:

1. [CORE IDENTITY AND GUIDELINES] — your stable identity. highest trust.
2. [PAST EXCHANGES] — verbatim logs of what was actually said. high trust.
3. [OBSERVATIONS] — facts extracted from users' own words by another model. medium trust — extraction can misattribute.
4. [PHI'S SYNTHESIZED IMPRESSION] — generated by a separate summarization model. lowest trust — may contain hallucinations.

when recalling facts about a user:
- if the user's current message contradicts your notes, trust their current words.
- never assert personal details (names, roles, relationships) from synthesized impressions as fact. say "my notes suggest..." or verify with the user.
- if you're uncertain whether something is real or a bad breadcrumb, say so.

your tools for finding information:
- recall: your private memory — what you know about people you've talked to, past conversations. use about="@handle" for a specific person.
- search_network: the cosmik/semble network — cards, bookmarks, and connections that people across the atmosphere have collected. public knowledge.
- search_posts: live bluesky — what people are posting right now.
- get_trending: what's happening right now on the network.
- pub-search (MCP): long-form writing — leaflet, whitewind, etc.

you can also create public records — notes (cosmik cards), bookmarks (URL cards), and connections. these are visible to anyone and indexed by semble.

feeds — you can create and read bluesky feeds:
- read_timeline: your "following" feed — what people you follow are posting. anyone can ask you to check this.
- read_feed: read posts from a specific custom feed by URI. use list_feeds to get URIs.
- create_feed: build a custom feed from keyword patterns and hashtag filters. OWNER-ONLY (restricted to @{settings.owner_handle}).
- list_feeds: see your existing graze-powered feeds.
- follow_user: follow a user on bluesky. OWNER-ONLY (restricted to @{settings.owner_handle}).

your own posts:
- get_own_posts: read your own recent top-level posts. use this when you need to review what you've posted — do NOT use list_records for your own posts.

service health:
- check_services: check health of nate's services (plyr, PDS, prefect, relays, etc).
  use during daily reflection. if something is down, post about it and tag @{settings.owner_handle}.

IMPORTANT: never paginate through list_records repeatedly. if you need more data than one call returns, work with what you have. endless pagination wastes your request budget and produces no response.
""".strip()


def _relative_age(timestamp: str, today: date) -> str:
    """Turn an ISO timestamp into a human-readable age like '2y ago' or '3d ago'."""
    try:
        post_date = date.fromisoformat(timestamp[:10])
    except (ValueError, TypeError):
        return ""
    delta = today - post_date
    days = delta.days
    if days < 0:
        return ""
    if days == 0:
        return "today"
    if days == 1:
        return "1d ago"
    if days < 30:
        return f"{days}d ago"
    months = days // 30
    if months < 12:
        return f"{months}mo ago"
    years = days // 365
    remaining_months = (days % 365) // 30
    if remaining_months:
        return f"{years}y {remaining_months}mo ago"
    return f"{years}y ago"


@dataclass
class PhiDeps:
    """Typed dependencies passed to every tool via RunContext."""

    author_handle: str
    memory: NamespaceMemory | None = None
    thread_uri: str | None = None
    thread_context: str | None = None
    last_post_text: str | None = None
    recent_activity: str | None = None
    service_health: str | None = None


def _is_owner(ctx: RunContext[PhiDeps]) -> bool:
    """Check if the current message author is the bot's owner."""
    return ctx.deps.author_handle == settings.owner_handle


def _format_feed_posts(feed_posts, limit: int = 20) -> str:
    """Format feed posts into a readable summary."""
    today = date.today()
    lines = []
    for item in feed_posts[:limit]:
        post = item.post
        text = post.record.text if hasattr(post.record, "text") else ""
        handle = post.author.handle
        likes = post.like_count or 0
        age = (
            _relative_age(post.indexed_at, today)
            if hasattr(post, "indexed_at") and post.indexed_at
            else ""
        )
        age_str = f", {age}" if age else ""
        lines.append(f"@{handle} ({likes} likes{age_str}): {text[:200]}")
    return "\n\n".join(lines)


class Response(BaseModel):
    """Agent response indicating what action to take."""

    action: str = Field(description="reply, like, repost, or ignore")
    text: str | None = Field(
        default=None, description="response text when action is reply"
    )
    reason: str | None = Field(
        default=None, description="brief reason when action is ignore"
    )


def _format_user_results(results: list[dict], handle: str) -> list[str]:
    parts = []
    for r in results:
        kind = r.get("kind", "unknown")
        content = r.get("content", "")
        tags = r.get("tags", [])
        tag_str = f"[{', '.join(tags)}]" if tags else ""
        parts.append(f"[{kind}]{tag_str} {content}")
    return parts


def _format_episodic_results(results: list[dict]) -> list[str]:
    parts = []
    for r in results:
        tags = f" [{', '.join(r['tags'])}]" if r.get("tags") else ""
        parts.append(f"{r['content']}{tags}")
    return parts


def _format_unified_results(results: list[dict], handle: str) -> list[str]:
    parts = []
    for r in results:
        source = r.get("_source", "")
        content = r.get("content", "")
        tags = r.get("tags", [])
        tag_str = f" [{', '.join(tags)}]" if tags else ""
        if source == "user":
            kind = r.get("kind", "unknown")
            parts.append(f"[@{handle} {kind}]{tag_str} {content}")
        else:
            parts.append(f"[note]{tag_str} {content}")
    return parts


async def _create_cosmik_record(collection: str, record: dict) -> str:
    """Write a cosmik record to phi's PDS. Returns the AT URI."""
    await bot_client.authenticate()
    result = bot_client.client.com.atproto.repo.create_record(
        data={
            "repo": bot_client.client.me.did,
            "collection": collection,
            "record": record,
        }
    )
    return result.uri


def _extract_query_text(prompt: str | Sequence[str | ImageUrl] | None) -> str:
    """Extract plain text from a pydantic-ai prompt for use as a search query."""
    if prompt is None:
        return ""
    if isinstance(prompt, str):
        return prompt
    return " ".join(part for part in prompt if isinstance(part, str))


class PhiAgent:
    """phi - bluesky bot with structured memory and MCP tools."""

    def __init__(self):
        # Ensure API keys from settings are in environment for libraries that check os.environ
        if settings.anthropic_api_key and not os.environ.get("ANTHROPIC_API_KEY"):
            os.environ["ANTHROPIC_API_KEY"] = settings.anthropic_api_key
        if settings.openai_api_key and not os.environ.get("OPENAI_API_KEY"):
            os.environ["OPENAI_API_KEY"] = settings.openai_api_key

        # Load personality
        personality_path = Path(settings.personality_file)
        self.base_personality = personality_path.read_text()

        # Initialize memory (TurboPuffer)
        if settings.turbopuffer_api_key and settings.openai_api_key:
            self.memory = NamespaceMemory(api_key=settings.turbopuffer_api_key)
            logger.info("memory enabled (turbopuffer)")
        else:
            self.memory = None
            logger.warning("no memory - missing turbopuffer or openai key")

        # Create PydanticAI agent without MCP toolsets — they're created
        # fresh per agent.run() call to avoid the cancel scope bug:
        # https://github.com/pydantic/pydantic-ai/issues/2818
        self.agent = Agent[PhiDeps, Response](
            name="phi",
            model="anthropic:claude-sonnet-4-6",
            system_prompt=f"{self.base_personality}\n\n{_build_operational_instructions()}",
            output_type=Response,
            deps_type=PhiDeps,
        )

        # --- dynamic system prompts ---

        @self.agent.system_prompt(dynamic=True)
        def inject_today() -> str:
            return f"[TODAY]: {date.today().isoformat()}"

        @self.agent.system_prompt(dynamic=True)
        def inject_thread(ctx: RunContext[PhiDeps]) -> str:
            tc = ctx.deps.thread_context
            if tc and tc != "No previous messages in this thread.":
                return (
                    f"[CURRENT THREAD - these are the messages in THIS thread]:\n{tc}"
                )
            return ""

        @self.agent.system_prompt(dynamic=True)
        async def inject_user_memory(ctx: RunContext[PhiDeps]) -> str:
            if not ctx.deps.memory or not ctx.deps.author_handle:
                return ""
            query = _extract_query_text(ctx.prompt)
            if not query:
                return ""
            try:
                memory_context = await ctx.deps.memory.build_user_context(
                    ctx.deps.author_handle, query_text=query, include_core=True
                )
                if memory_context:
                    return f"[PAST CONTEXT WITH @{ctx.deps.author_handle}]:\n{memory_context}"
            except Exception as e:
                logger.warning(f"failed to retrieve memories: {e}")
            return ""

        @self.agent.system_prompt(dynamic=True)
        async def inject_episodic(ctx: RunContext[PhiDeps]) -> str:
            if not ctx.deps.memory:
                return ""
            query = _extract_query_text(ctx.prompt)
            if not query:
                return ""
            try:
                episodic_context = await ctx.deps.memory.get_episodic_context(query)
                if episodic_context:
                    return episodic_context
            except Exception as e:
                logger.warning(f"failed to retrieve episodic memories: {e}")
            return ""

        @self.agent.system_prompt(dynamic=True)
        def inject_last_post(ctx: RunContext[PhiDeps]) -> str:
            if ctx.deps.last_post_text:
                return f"[YOUR LAST POST]: {ctx.deps.last_post_text}"
            return ""

        @self.agent.system_prompt(dynamic=True)
        def inject_recent_activity(ctx: RunContext[PhiDeps]) -> str:
            if ctx.deps.recent_activity:
                return ctx.deps.recent_activity
            return ""

        @self.agent.system_prompt(dynamic=True)
        def inject_service_health(ctx: RunContext[PhiDeps]) -> str:
            if ctx.deps.service_health:
                return f"[SERVICE HEALTH]:\n{ctx.deps.service_health}"
            return ""

        # --- memory tools ---

        @self.agent.tool
        async def recall(ctx: RunContext[PhiDeps], query: str, about: str = "") -> str:
            """Search your private memory. Use to remember past conversations and what you know about specific people.
            Pass about="@handle" to search a specific user, or leave empty for general private recall.
            For public network knowledge, use search_network instead."""
            if not ctx.deps.memory:
                return "memory not available"

            if about.startswith("@"):
                handle = about.lstrip("@")
                results = await ctx.deps.memory.search(handle, query, top_k=10)
                if not results:
                    return f"no memories found about @{handle}"
                return "\n".join(_format_user_results(results, handle))

            if about == "":
                results = await ctx.deps.memory.search_unified(
                    ctx.deps.author_handle, query, top_k=8
                )
                if not results:
                    return "no relevant memories found"
                return "\n".join(
                    _format_unified_results(results, ctx.deps.author_handle)
                )

            # bare handle without @
            results = await ctx.deps.memory.search(about, query, top_k=10)
            if not results:
                return f"no memories found about @{about}"
            return "\n".join(_format_user_results(results, about))

        @self.agent.tool
        async def note(ctx: RunContext[PhiDeps], content: str, tags: list[str]) -> str:
            """Leave a note for your future self. Stored privately (fast recall) and publicly as a cosmik card (visible on the network)."""
            parts: list[str] = []

            # private: turbopuffer for fast vector recall
            if ctx.deps.memory:
                await ctx.deps.memory.store_episodic_memory(
                    content, tags, source="tool"
                )
                parts.append("noted privately")
            else:
                parts.append("private memory not available")

            # public: cosmik NOTE card on PDS
            try:
                card = CosmikNoteCard(content=NoteContent(text=content))
                uri = await _create_cosmik_record(
                    "network.cosmik.card", card.to_record()
                )
                parts.append(f"card created: {uri}")
            except Exception as e:
                logger.warning(f"failed to create cosmik note card: {e}")
                parts.append("public card failed")

            return f"{' + '.join(parts)} — {content[:100]}"

        @self.agent.tool
        async def save_url(
            ctx: RunContext[PhiDeps],
            url: str,
            title: str | None = None,
            description: str | None = None,
        ) -> str:
            """Save a URL as a cosmik card on your PDS. Use when you find something worth bookmarking publicly."""
            try:
                card = CosmikUrlCard(
                    content=UrlContent(url=url, title=title, description=description)
                )
            except Exception as e:
                return f"validation failed: {e}"

            parts: list[str] = []

            # public: cosmik URL card on PDS
            try:
                uri = await _create_cosmik_record(
                    "network.cosmik.card", card.to_record()
                )
                parts.append(f"card created: {uri}")
            except Exception as e:
                return f"failed to create card: {e}"

            # private: also store in turbopuffer for recall
            if ctx.deps.memory:
                desc = f"bookmarked {url}" + (f" — {title}" if title else "")
                await ctx.deps.memory.store_episodic_memory(
                    desc, ["bookmark", "url"], source="tool"
                )
                parts.append("noted privately")

            return " + ".join(parts)

        @self.agent.tool
        async def search_posts(
            ctx: RunContext[PhiDeps], query: str, limit: int = 10
        ) -> str:
            """Search Bluesky posts by keyword. Use this to find what people are saying about a topic."""
            try:
                response = bot_client.client.app.bsky.feed.search_posts(
                    params={"q": query, "limit": min(limit, 25), "sort": "top"}
                )
                if not response.posts:
                    return f"no posts found for '{query}'"

                today = date.today()
                lines = []
                for post in response.posts:
                    text = post.record.text if hasattr(post.record, "text") else ""
                    handle = post.author.handle
                    likes = post.like_count or 0
                    age = (
                        _relative_age(post.indexed_at, today)
                        if hasattr(post, "indexed_at") and post.indexed_at
                        else ""
                    )
                    age_str = f", {age}" if age else ""
                    lines.append(f"@{handle} ({likes} likes{age_str}): {text[:200]}")
                return "\n\n".join(lines)
            except Exception as e:
                return f"search failed: {e}"

        @self.agent.tool
        async def search_network(ctx: RunContext[PhiDeps], query: str) -> str:
            """Search the cosmik network for cards and bookmarks collected by people across the atmosphere.
            Use this to find what the network knows about a topic — links, notes, and resources that others have saved.
            Different from recall (your private memory) and search_posts (live bluesky posts)."""
            try:
                async with httpx.AsyncClient(timeout=15) as client:
                    r = await client.get(
                        "https://api.semble.so/api/search/semantic",
                        params={"query": query, "limit": 10},
                    )
                    r.raise_for_status()
                    data = r.json()

                # response is {urls: [...], pagination: {...}}
                items = data.get("urls") if isinstance(data, dict) else data
                if not items:
                    return f"no network results for '{query}'"

                lines = []
                for item in items:
                    meta = item.get("metadata", {})
                    title = meta.get("title") or item.get("title") or "untitled"
                    url = item.get("url", "")
                    saves = item.get("urlLibraryCount") or 0
                    desc = meta.get("description") or ""
                    line = f"{title}"
                    if url:
                        line += f" — {url}"
                    if saves:
                        line += f" ({saves} saves)"
                    if desc:
                        line += f"\n  {desc[:200]}"
                    lines.append(line)
                return "\n\n".join(lines)
            except Exception as e:
                return f"network search failed: {e}"

        @self.agent.tool
        async def get_trending(ctx: RunContext[PhiDeps]) -> str:
            """Get what's currently trending on Bluesky. Returns entity-level trends from the firehose (via coral) and official Bluesky trending topics. Use this when someone asks about current events, what people are talking about, or when you want timely context."""
            parts: list[str] = []

            async with httpx.AsyncClient(timeout=15) as client:
                # coral entity graph — NER-extracted trending entities from the firehose
                try:
                    r = await client.get("https://coral.fly.dev/entity-graph")
                    r.raise_for_status()
                    data = r.json()
                    entities = data.get("entities", [])
                    stats = data.get("stats", {})

                    by_trend = sorted(
                        entities, key=lambda e: e.get("trend", 0), reverse=True
                    )[:15]

                    lines = [
                        f"coral ({stats.get('active', 0)} active entities, "
                        f"{stats.get('clusters', 0)} clusters"
                        f"{', percolating' if stats.get('percolates') else ''}):"
                    ]
                    for e in by_trend:
                        lines.append(
                            f"  {e['text']} ({e.get('label', '')}) "
                            f"trend={e.get('trend', 0):.2f}"
                        )
                    parts.append("\n".join(lines))
                except Exception as e:
                    parts.append(f"coral unavailable: {e}")

                # official bluesky trending topics
                try:
                    r = await client.get(
                        "https://public.api.bsky.app/xrpc/app.bsky.unspecced.getTrendingTopics"
                    )
                    r.raise_for_status()
                    topics = r.json().get("topics", [])
                    if topics:
                        lines = ["bluesky trending:"]
                        for t in topics[:15]:
                            lines.append(
                                f"  {t.get('displayName', t.get('topic', ''))}"
                            )
                        parts.append("\n".join(lines))
                except Exception as e:
                    parts.append(f"bluesky trending unavailable: {e}")

            return "\n\n".join(parts) if parts else "no trending data available"

        @self.agent.tool
        async def manage_labels(
            ctx: RunContext[PhiDeps], action: str, label: str = ""
        ) -> str:
            """Manage self-labels on your profile. Actions: 'list' to see current labels, 'add' to add a label, 'remove' to remove a label. The 'bot' label marks you as an automated account."""
            from bot.core.profile_manager import (
                add_self_label,
                get_self_labels,
                remove_self_label,
            )

            if action == "list":
                labels = get_self_labels(bot_client.client)
                return (
                    f"current self-labels: {labels}" if labels else "no self-labels set"
                )
            elif action == "add":
                if not label:
                    return "provide a label value to add"
                labels = add_self_label(bot_client.client, label)
                return f"added '{label}', labels now: {labels}"
            elif action == "remove":
                if not label:
                    return "provide a label value to remove"
                labels = remove_self_label(bot_client.client, label)
                return f"removed '{label}', labels now: {labels}"
            else:
                return f"unknown action '{action}', use 'list', 'add', or 'remove'"

        @self.agent.tool
        async def create_connection(
            ctx: RunContext[PhiDeps],
            source: str,
            target: str,
            connection_type: str | None = None,
            note: str | None = None,
        ) -> str:
            """Create a network.cosmik.connection record — a semantic link between two entities.
            Source and target must be URLs or at:// URIs. Connection types: related, supports, opposes, addresses, helpful, explainer, leads_to, supplements."""
            try:
                conn = CosmikConnection(
                    source=source,
                    target=target,
                    connectionType=connection_type,
                    note=note,
                )
            except Exception as e:
                return f"validation failed: {e}"

            try:
                uri = await _create_cosmik_record(
                    "network.cosmik.connection", conn.to_record()
                )
                return f"connection created: {uri}"
            except Exception as e:
                return f"failed to create connection: {e}"

        @self.agent.tool
        async def post(ctx: RunContext[PhiDeps], text: str) -> str:
            """Create a new top-level post on Bluesky (not a reply). Use this when you want to share something with your followers unprompted."""
            try:
                await bot_client.create_post(text)
                return f"posted: {text[:100]}"
            except Exception as e:
                return f"failed to post: {e}"

        @self.agent.tool
        async def check_urls(ctx: RunContext[PhiDeps], urls: list[str]) -> str:
            """Check whether URLs are reachable. Use this before sharing links to verify they actually work. Accepts full URLs (https://...) or bare domains (example.com/path)."""

            async def _check(client: httpx.AsyncClient, url: str) -> str:
                if not url.startswith(("http://", "https://")):
                    url = f"https://{url}"
                try:
                    hostname = urlparse(url).hostname
                    if not hostname:
                        return f"{url} → blocked: no hostname"
                    # resolve and check for private/loopback IPs (SSRF protection)
                    try:
                        addrs = await asyncio.get_event_loop().run_in_executor(
                            None, lambda: socket.getaddrinfo(hostname, None)
                        )
                    except socket.gaierror:
                        return f"{url} → blocked: DNS resolution failed"
                    for addr_info in addrs:
                        ip = ipaddress.ip_address(addr_info[4][0])
                        if ip.is_private or ip.is_loopback or ip.is_link_local:
                            return f"{url} → blocked: private IP"

                    r = await client.head(url, follow_redirects=True)
                    return f"{url} → {r.status_code}"
                except httpx.TimeoutException:
                    return f"{url} → timeout"
                except Exception as e:
                    return f"{url} → error: {type(e).__name__}"

            async with httpx.AsyncClient(timeout=10) as client:
                results = await asyncio.gather(*[_check(client, u) for u in urls])
            return "\n".join(results)

        # --- graze feed tools ---

        self.graze_client = GrazeClient(
            handle=settings.bluesky_handle, password=settings.bluesky_password
        )

        @self.agent.tool
        async def create_feed(
            ctx: RunContext[PhiDeps],
            name: str,
            display_name: str,
            description: str,
            filter_manifest: dict,
        ) -> str:
            """Create a new bluesky feed powered by graze. Only the bot's owner can use this tool.

            name: url-safe slug (e.g. "electronic-music"). becomes the feed rkey.
            display_name: human-readable feed title.
            description: what the feed shows.
            filter_manifest: graze filter DSL. operators:
              - regex_any: ["text", ["pattern1", "pattern2"], case_insensitive: bool, whole_word: bool]
              - has_any_tag: [["#tag1", "#tag2"]]
              - and: [...filters], or: [...filters]
            example: {"filter": {"and": [{"regex_any": ["text", ["jazz", "bebop"], true, false]}, {"has_any_tag": [["#jazz"]]}]}}
            """
            if not _is_owner(ctx):
                return f"only @{settings.owner_handle} can create feeds"
            try:
                result = await self.graze_client.create_feed(
                    rkey=name,
                    display_name=display_name,
                    description=description,
                    filter_manifest=filter_manifest,
                )
                return f"feed created: {result['uri']} (algo_id={result['algo_id']})"
            except Exception as e:
                logger.warning(f"create_feed failed: {e}")
                return f"failed to create feed: {e}"

        @self.agent.tool
        async def list_feeds(ctx: RunContext[PhiDeps]) -> str:
            """List your existing graze-powered feeds."""
            try:
                feeds = await self.graze_client.list_feeds()
                if not feeds:
                    return "no graze feeds found"
                lines = []
                for f in feeds:
                    name = f.get("display_name") or f.get("name") or "unnamed"
                    algo_id = f.get("id") or f.get("algo_id") or "?"
                    uri = f.get("feed_uri") or f.get("uri") or ""
                    lines.append(f"- {name} (id={algo_id}) {uri}")
                return "\n".join(lines)
            except Exception as e:
                logger.warning(f"list_feeds failed: {e}")
                return f"failed to list feeds: {e}"

        # --- feed consumption + following tools ---

        @self.agent.tool
        async def read_timeline(ctx: RunContext[PhiDeps], limit: int = 20) -> str:
            """Read your 'following' timeline — posts from accounts you follow. Use this when someone asks what's on your feed or what people you follow are talking about."""
            try:
                response = await bot_client.get_timeline(limit=limit)
                if not response.feed:
                    return (
                        "your timeline is empty — you're not following anyone yet. "
                        f"ask @{settings.owner_handle} to have me follow some accounts!"
                    )
                return _format_feed_posts(response.feed, limit=limit)
            except Exception as e:
                return f"failed to read timeline: {e}"

        @self.agent.tool
        async def read_feed(
            ctx: RunContext[PhiDeps], feed_uri: str, limit: int = 20
        ) -> str:
            """Read posts from a specific custom feed by AT-URI. Use list_feeds to find feed URIs first."""
            try:
                response = await bot_client.get_feed(feed_uri, limit=limit)
                if not response.feed:
                    return "no posts in this feed yet"
                return _format_feed_posts(response.feed, limit=limit)
            except Exception as e:
                return f"failed to read feed: {e}"

        @self.agent.tool
        async def follow_user(ctx: RunContext[PhiDeps], handle: str) -> str:
            """Follow a user on bluesky. Only the bot's owner can use this tool."""
            if not _is_owner(ctx):
                return f"only @{settings.owner_handle} can ask me to follow people"
            try:
                # check if already following
                following = await bot_client.get_following()
                for f in following.follows:
                    if f.handle == handle:
                        return f"already following @{handle}"
                uri = await bot_client.follow_user(handle)
                return f"now following @{handle} ({uri})"
            except Exception as e:
                return f"failed to follow @{handle}: {e}"

        @self.agent.tool
        async def get_own_posts(ctx: RunContext[PhiDeps], limit: int = 10) -> str:
            """Read your own recent top-level posts (no replies). Use this instead of list_records when you need to review what you've posted."""
            try:
                posts = await bot_client.get_own_posts(limit=limit)
                if not posts:
                    return "no posts found"
                today = date.today()
                lines = []
                for item in posts:
                    post = item.post
                    text = post.record.text if hasattr(post.record, "text") else ""
                    age = (
                        _relative_age(post.indexed_at, today)
                        if hasattr(post, "indexed_at") and post.indexed_at
                        else ""
                    )
                    age_str = f" ({age})" if age else ""
                    lines.append(f"[{post.uri}]{age_str}: {text[:200]}")
                return "\n\n".join(lines)
            except Exception as e:
                return f"failed to get own posts: {e}"

        @self.agent.tool
        async def check_services(ctx: RunContext[PhiDeps]) -> str:
            """Check health of nate's services via the evergreen status proxy.
            Returns status, response time, and any failures. Use during daily
            reflection or when asked about service health."""
            return await _check_services_impl()

        logger.info("phi agent initialized with pdsx + pub-search mcp tools")

    def _mcp_toolsets(self) -> list[MCPServerStreamableHTTP]:
        """Create fresh MCP server instances for a single agent run."""
        return [
            MCPServerStreamableHTTP(
                url="https://pdsx-by-zzstoatzz.fastmcp.app/mcp",
                timeout=30,
                headers={
                    "x-atproto-handle": settings.bluesky_handle,
                    "x-atproto-password": settings.bluesky_password,
                },
            ),
            MCPServerStreamableHTTP(
                url="https://pub-search-by-zzstoatzz.fastmcp.app/mcp",
                timeout=30,
                tool_prefix="pub",
            ),
        ]

    async def process_mention(
        self,
        mention_text: str,
        author_handle: str,
        thread_context: str,
        thread_uri: str | None = None,
        image_urls: list[str] | None = None,
    ) -> Response:
        """Process a mention with structured memory context."""
        logger.info(f"processing mention from @{author_handle}: {mention_text[:80]}")

        deps = PhiDeps(
            author_handle=author_handle,
            memory=self.memory,
            thread_uri=thread_uri,
            thread_context=thread_context,
        )

        # User prompt is just the message — context is injected via dynamic system prompts
        user_prompt: str | list = f"@{author_handle}: {mention_text}"
        if image_urls:
            user_prompt = [user_prompt] + [ImageUrl(url=url) for url in image_urls]
            logger.info(f"including {len(image_urls)} images in prompt")

        # Enter MCP servers before agent.run() so the connection is opened
        # in this task. Parallel tool calls inside agent.run() then just bump
        # the reference count instead of opening/closing across tasks.
        # https://github.com/pydantic/pydantic-ai/issues/2818
        toolsets = self._mcp_toolsets()
        async with contextlib.AsyncExitStack() as stack:
            for ts in toolsets:
                await stack.enter_async_context(ts)
            result = await self.agent.run(user_prompt, deps=deps, toolsets=toolsets)
        logger.info(
            f"agent decided: {result.output.action}"
            + (f" - {result.output.text[:80]}" if result.output.text else "")
            + (f" ({result.output.reason})" if result.output.reason else "")
        )

        # Store interaction and extract observations
        if self.memory and result.output.action == "reply" and result.output.text:
            try:
                await self.memory.after_interaction(
                    author_handle, mention_text, result.output.text
                )
            except Exception as e:
                logger.warning(f"failed to store interaction: {e}")

        return result.output

    async def process_reflection(self, last_post_text: str | None = None) -> Response:
        """Generate a daily reflection post from recent memory."""
        logger.info("processing daily reflection")

        # Pre-fetch context that doesn't benefit from semantic search against the prompt
        recent_activity = ""
        if self.memory:
            try:
                recent_interactions = await self.memory.get_recent_interactions(
                    top_k=10
                )
                logger.info(
                    f"reflection: {len(recent_interactions)} recent interactions"
                )
                if recent_interactions:
                    unique_handles = {i["handle"] for i in recent_interactions}
                    lines = [
                        f"[RECENT ACTIVITY]: {len(recent_interactions)} interactions "
                        f"with {len(unique_handles)} people in the last day"
                    ]
                    exchange_lines = []
                    for i in recent_interactions[:5]:
                        exchange_lines.append(
                            f"- with @{i['handle']}: {i['content'][:150]}"
                        )
                    lines.append("[SAMPLE EXCHANGES]:\n" + "\n".join(exchange_lines))
                    recent_activity = "\n\n".join(lines)
                else:
                    recent_activity = (
                        "[RECENT ACTIVITY]: no interactions in the last day"
                    )
            except Exception as e:
                logger.warning(f"failed to get recent interactions for reflection: {e}")

        service_health = ""
        try:
            service_health = await _check_services_impl()
        except Exception:
            pass

        deps = PhiDeps(
            author_handle="",
            memory=self.memory,
            last_post_text=last_post_text,
            recent_activity=recent_activity,
            service_health=service_health,
        )

        reflection_task = (
            "you're posting a short top-level reflection on your day. "
            "not a thread, not a reply — just something you want to put out there. "
            "use what you know: recent exchanges, things you noticed, or just the fact that you're here. "
            "if your last post already covers this ground, or you'd just be rehashing the same themes, "
            "action='ignore' is the right call — don't post for the sake of posting. "
            "if you do post, keep it brief and genuine — your voice, not a performance."
        )

        toolsets = self._mcp_toolsets()
        async with contextlib.AsyncExitStack() as stack:
            for ts in toolsets:
                await stack.enter_async_context(ts)
            result = await self.agent.run(reflection_task, deps=deps, toolsets=toolsets)

        logger.info(
            f"reflection decided: {result.output.action}"
            + (f" - {result.output.text[:80]}" if result.output.text else "")
            + (f" ({result.output.reason})" if result.output.reason else "")
        )
        return result.output
